baseurl = "http://andreimihu.com/"
title = "Always a Work in Progress"
languageCode = "en-us"
disqusShortname = "andreimihu"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Andrei Mihu"

[permalinks]
    # Change the permalink format for the 'post' content type.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[params]
    # Default page metadata, used when the specific page doesn't set its own.
    defaultDescription = "Tech musings, current projects and more about me, Andrei Mihu!"
    defaultKeywords = "andrei mihu,home,website,blog"

    # Changes sidebar background and link/accent colours.
    # This also works: "theme-base-0c layout-reverse", or just "layout-reverse".
	theme = "theme-base-0c"

    # Select a syntax highight.
    highlight = "solarized_light"

    # Tagline to display under the author name in the sidebar, keep it short.
    # You can use markdown here.
	tagline = "The pursuit of massive server-side scale with [Elixir](http://elixir-lang.org)"

    # Metadata used to drive integrations.
	googleAuthorship = "116158239234656634929"
    googleAnalytics = "UA-44918664-1"
    gravatarHash = "4ad01d4e7c9463cfb5119bdf07d5fcfa"

    # Sidebar social links.
    github = "https://github.com/zyro"
    bitbucket = ""
    linkedin = "http://www.linkedin.com/in/andreimihu"
    googleplus = ""
    facebook = ""
    twitter = ""
